### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=ofJecp&redirect_uri=http://www.51xuecheng.cn


### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=t1&password=111111

###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDI0LTA0LTE2VDEwOjM4OjU0XCIsXCJpZFwiOlwiNzJhZmI0N2YtY2VmZi00OTVlLTllYzEtOTc1MmE2ZmY2NDM3XCIsXCJuYW1lXCI6XCLpu5jpu5hcIixcIm5pY2tuYW1lXCI6XCLpu5jpu5hcIixcInBlcm1pc3Npb25zXCI6W10sXCJzZXhcIjpcIjBcIixcInN0YXR1c1wiOlwiMVwiLFwidXNlcm5hbWVcIjpcIm92MmJ6NUFESko2WU9NU3dlRXdKWWRubTRVQlFcIixcInV0eXBlXCI6XCIxMDEwMDFcIixcInd4VW5pb25pZFwiOlwibzZ2RVV1S3FmelVfMElNTmVRV0lMRkptQjJXb1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MTMzMzI1MjYsImF1dGhvcml0aWVzIjpbInhjX3N5c21hbmFnZXJfZG9jIiwieGNfdGVhY2htYW5hZ2VyX2NvdXJzZV9saXN0IiwieGNfc3lzbWFuYWdlciIsInhjX3N5c21hbmFnZXJfY29tcGFueSIsInhjX3N5c21hbmFnZXJfbG9nIl0sImp0aSI6ImYyOGM2Mzk3LTMxOGEtNDIxNS1hM2EzLTllMjU3NDllMmFhOSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.Kmz32vSnNHlqMuOZFyrkMBfjmTl_dtDrtMerLfY5Eh4

### 密码模式,请求AuthParamsDto参数
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"t1","password":"111111","authType":"password"}

### 密码模式,请求AuthParamsDto参数
POST {{auth_host}}/auth/wxLogin
### 密码模式,请求AuthParamsDto参数
GET {{auth_host}}/auth/wxLogin

### 查看
GET {{auth_host}}/auth/getCodeItem/833347DF84E33F21FC607776BE837DAA1712998132903