### 查询课程信息
POST {{content_host}}/content/course/list?pageSize=2&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 101,
  "originalPrice":100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "java网络编程高级1111",
  "pic": "fdsd",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "dsadasdasfasaasd",
  "grade": "204001",
  "description": "java网络编程高级java网络编程高级java网络编程高级"
}

### 制造异常
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 101,
  "originalPrice":100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "fdsd",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "dsadasdasfasaasd",
  "grade": "204001",
  "description": "java网络编程高级java网络编程高级java网络编程高级"
}

### 根据课程id查询课程信息
GET {{content_host}}/content/course/40
Content-Type: application/json


### 修改课程
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "auditStatus": "202003",
  "changeDate": "2024-01-19 12:40:39",
  "charge": "201000",
  "companyId": "1232141425",
  "createDate": "2024-01-18 14:41:14",
  "description": "java测试00120240118java测试00120240118",
  "grade": "204001",
  "id": "147",
  "mt": "1-10",
  "mtName": "研发管理",
  "name": "java测试003",
  "phone": "122222",
  "pic": "",
  "price": 0,
  "qq": "122222",
  "st": "1-10-2",
  "stName": "软件设计",
  "status": "203001",
  "tags": "java测试003",
  "teachmode": "200003",
  "users": "java测试00120240118java测试00120240118java测试00120240118",
  "validDays": 365,
  "wechat": "122222"
}

### 课程计划查询
GET {{gateway_host}}/content/teachplan/117/tree-nodes
Content-Type: application/json

### 修改老师
PUT {{content_host}}/content/courseTeacher
Content-Type: application/json

{
  "id": 21,
  "courseId": 79,
  "teacherName": "李四郎",
  "position": "培训二级讲师",
  "introduction": "张天师传人，负责推广",
  "photograph": null,
  "position": "培训二级讲师",
  "teacherName": "李四郎"
}

### 制造异常
POST {{content_host}}/content/coursepublish/123
Content-Type: application/json


