### 申请验证码
POST {{checkcode_host}}/checkcode/pic

### 校验验证码
POST {{checkcode_host}}/checkcode/verify?key=checkcode:c920115f6a1b4de3a0bfcefa3656c537&code=w83p


### 申请验证码
POST {{checkcode_host}}/checkcode/phone?param1=aimeinvshen@126.com

